"""Batch dashboard — one sortable, filterable HTML table over many submissions."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from jinja2 import Template

from .. import __version__

# autoescape: submission ids, author URLs and verdict strings are untrusted text.
_TPL = Template(r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>reprobe — batch</title>
<style>
 body{font:14px/1.5 system-ui,sans-serif;margin:0;background:#f6f7f9;color:#1a1a1a}
 .wrap{max-width:1200px;margin:0 auto;padding:24px}
 h1{font-size:20px;margin:0 0 2px} .muted{color:#666;font-size:12px}
 .strip{background:#fff;border:1px solid #e4e6eb;border-radius:8px;padding:8px 12px;margin:10px 0;font-size:13px}
 table{border-collapse:collapse;width:100%;background:#fff;border:1px solid #e4e6eb;border-radius:8px;overflow:hidden}
 th,td{border-bottom:1px solid #eee;padding:8px 10px;text-align:left;font-size:13px}
 th{background:#f0f1f3;cursor:pointer;user-select:none} code{font-size:12px}
 .granted{color:#1e7d34;font-weight:600}.candidate{color:#a06800;font-weight:600}.notmet,.fail{color:#b42318;font-weight:600}.noteval{color:#888}
 .flag{display:inline-block;background:#fde8e8;color:#b42318;border-radius:4px;padding:1px 6px;font-size:11px;margin:1px}
 #q{margin:10px 0;padding:6px 10px;border:1px solid #ccd;border-radius:6px;width:280px;font-size:13px}
</style></head><body><div class="wrap">
<h1>reprobe batch — {{ rows|length }} submissions</h1>
<div class="muted">{{ version }} · generated {{ generated }}</div>
<div class="strip">
 <b>Available</b> {% for k, v in avail_counts %}<span class="{{ cls.get(k, '') }}">{{ k }}: {{ v }}</span>{% if not loop.last %} · {% endif %}{% endfor %}
 &nbsp;|&nbsp; <b>Functional</b> {% for k, v in func_counts %}<span class="{{ cls.get(k, '') }}">{{ k }}: {{ v }}</span>{% if not loop.last %} · {% endif %}{% endfor %}
 &nbsp;|&nbsp; <b>needs human review: {{ review_n }}</b>
</div>
<input id="q" type="search" placeholder="filter rows…">
<table id="t"><thead><tr>
 <th>#</th><th>Submission</th><th>Source</th><th>Available</th><th>Functional</th><th>Verdict</th><th>Review</th><th>Flags</th></tr></thead><tbody>
{% for r in rows %}
 <tr><td>{{ loop.index }}</td>
 <td><a href="{{ r.report_html }}">{{ r.submission_id }}</a><br><code>{{ r.input }}</code></td>
 <td>{{ r.resolved_type }}</td>
 <td class="{{ r.available_cls }}">{{ r.available }}</td>
 <td class="{{ r.functional_cls }}">{{ r.functional }}</td>
 <td class="{{ r.verdict_cls }}">{{ r.verdict }}</td>
 <td>{{ 'yes' if r.review else '—' }}</td>
 <td>{% for f in r.flags %}<span class="flag">{{ f }}</span>{% endfor %}</td></tr>
{% endfor %}
</tbody></table>
<p class="muted">Click a header to sort (again to reverse); type to filter. Generated by reprobe.</p>
<script>
 const tb=document.querySelector('#t tbody');
 document.getElementById('q').oninput=e=>{const s=e.target.value.toLowerCase();
  [...tb.rows].forEach(r=>r.style.display=r.innerText.toLowerCase().includes(s)?'':'none');};
 document.querySelectorAll('#t th').forEach((th,i)=>th.onclick=()=>{
  const asc=th.dataset.d!=='a';
  document.querySelectorAll('#t th').forEach(h=>{delete h.dataset.d;h.textContent=h.textContent.replace(/ [▲▼]$/,'');});
  th.dataset.d=asc?'a':'d';th.textContent+=asc?' ▲':' ▼';
  [...tb.rows].sort((a,b)=>(asc?1:-1)*a.cells[i].innerText.localeCompare(b.cells[i].innerText,undefined,{numeric:true}))
   .forEach(r=>tb.appendChild(r));});
</script></div></body></html>""", autoescape=True)

_CLS = {"granted": "granted", "candidate": "candidate", "not-met": "notmet", "not-evaluated": "noteval"}
_VERDICT_CLS = {"runs": "granted", "runs-with-failures": "fail", "fetch-failed": "fail",
                "infra-error": "fail", "nothing-executed": "noteval", "not-run": "noteval"}


def render(reports: list[dict[str, Any]]) -> str:
    rows = []
    for rep in reports:
        acm = (rep.get("badges", {}).get("acm") or {})
        src = rep.get("source", {}) or {}
        verdict = rep.get("verdict", {}) or {}
        overall = verdict.get("overall") or "—"
        # flag the exceptional states a chair must look at, not routine ones
        flags = []
        if src.get("warnings"):
            flags.append("warnings")
        if src.get("anonymized"):
            flags.append("anonymized")
        if overall == "fetch-failed" or src.get("error"):
            flags.append("fetch-failed")
        if acm.get("functional") == "not-met":
            flags.append("not-met")
        if any((s or {}).get("status") == "timeout" for s in rep.get("steps") or []):
            flags.append("timeout")
        if overall in ("infra-error", "nothing-executed"):
            flags.append(overall)
        rows.append({
            "submission_id": rep.get("submission_id"),
            "input": src.get("input"),
            "resolved_type": src.get("resolved_type") or "—",
            "available": acm.get("available") or "—", "available_cls": _CLS.get(acm.get("available"), ""),
            "functional": acm.get("functional") or "—", "functional_cls": _CLS.get(acm.get("functional"), ""),
            "verdict": overall, "verdict_cls": _VERDICT_CLS.get(overall, ""),
            "review": bool(verdict.get("human_review_required")),
            "flags": flags,
            # href assumes the self-contained out/ bundle: the CLI copies each
            # per-submission report.html to <out>/<submission_id>/report.html.
            "report_html": f"{rep.get('submission_id')}/report.html",
        })

    def counts(key: str) -> list[tuple[str, int]]:
        c: dict[str, int] = {}
        for r in rows:
            c[r[key]] = c.get(r[key], 0) + 1
        return sorted(c.items())

    return _TPL.render(
        rows=rows, cls=_CLS,
        avail_counts=counts("available"), func_counts=counts("functional"),
        review_n=sum(1 for r in rows if r["review"]),
        version=f"reprobe {__version__}",
        generated=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )
