"""Batch dashboard — one sortable HTML table over many submissions."""

from __future__ import annotations

from typing import Any

from jinja2 import Template

_TPL = Template(r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><title>reprobe — batch</title>
<style>
 body{font:14px/1.5 system-ui,sans-serif;margin:0;background:#f6f7f9;color:#1a1a1a}
 .wrap{max-width:1200px;margin:0 auto;padding:24px}
 h1{font-size:20px} table{border-collapse:collapse;width:100%;background:#fff;border:1px solid #e4e6eb;border-radius:8px;overflow:hidden}
 th,td{border-bottom:1px solid #eee;padding:8px 10px;text-align:left;font-size:13px}
 th{background:#f0f1f3;cursor:pointer} code{font-size:12px}
 .granted{color:#1e7d34;font-weight:600}.candidate{color:#a06800;font-weight:600}.notmet,.fail{color:#b42318;font-weight:600}.noteval{color:#888}
 .flag{display:inline-block;background:#fde8e8;color:#b42318;border-radius:4px;padding:1px 6px;font-size:11px;margin:1px}
</style></head><body><div class="wrap">
<h1>reprobe batch — {{ rows|length }} submissions</h1>
<table id="t"><thead><tr>
 <th>#</th><th>Submission</th><th>Source</th><th>Available</th><th>Functional</th><th>Verdict</th><th>Flags</th></tr></thead><tbody>
{% for r in rows %}
 <tr><td>{{ loop.index }}</td>
 <td><a href="{{ r.report_html }}">{{ r.submission_id }}</a><br><code>{{ r.input }}</code></td>
 <td>{{ r.resolved_type }}</td>
 <td class="{{ r.available_cls }}">{{ r.available }}</td>
 <td class="{{ r.functional_cls }}">{{ r.functional }}</td>
 <td>{{ r.verdict }}</td>
 <td>{% for f in r.flags %}<span class="flag">{{ f }}</span>{% endfor %}</td></tr>
{% endfor %}
</tbody></table>
<p class="muted">Click a header to sort. Generated by reprobe.</p>
<script>
 document.querySelectorAll('#t th').forEach((th,i)=>th.onclick=()=>{
  const tb=th.closest('table').tBodies[0];
  [...tb.rows].sort((a,b)=>a.cells[i].innerText.localeCompare(b.cells[i].innerText,undefined,{numeric:true}))
   .forEach(r=>tb.appendChild(r));});
</script></div></body></html>""")

_CLS = {"granted": "granted", "candidate": "candidate", "not-met": "notmet", "not-evaluated": "noteval"}


def render(reports: list[dict[str, Any]]) -> str:
    rows = []
    for rep in reports:
        acm = (rep.get("badges", {}).get("acm") or {})
        src = rep.get("source", {})
        flags = list(src.get("warnings", []) and ["warnings"] or [])
        if src.get("anonymized"):
            flags.append("anonymized")
        if not src.get("checksum_verified"):
            flags.append("no-checksum")
        rows.append({
            "submission_id": rep.get("submission_id"),
            "input": src.get("input"),
            "resolved_type": src.get("resolved_type"),
            "available": acm.get("available"), "available_cls": _CLS.get(acm.get("available"), ""),
            "functional": acm.get("functional"), "functional_cls": _CLS.get(acm.get("functional"), ""),
            "verdict": rep.get("verdict", {}).get("overall"),
            "flags": flags,
            "report_html": f"{rep.get('submission_id')}/report.html",
        })
    return _TPL.render(rows=rows)
