"""Single-file HTML report (no external assets) for sharing with reviewers."""

from __future__ import annotations

from jinja2 import Template

from ..models import Report

_TPL = Template(r"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>reprobe — {{ r.submission_id }}</title>
<style>
 body{font:15px/1.5 system-ui,sans-serif;margin:0;background:#f6f7f9;color:#1a1a1a}
 .wrap{max-width:900px;margin:0 auto;padding:24px}
 h1{font-size:22px;margin:0 0 4px} .muted{color:#666;font-size:13px}
 .card{background:#fff;border:1px solid #e4e6eb;border-radius:10px;padding:16px 18px;margin:14px 0}
 .chip{display:inline-block;padding:3px 10px;border-radius:999px;font-size:13px;font-weight:600;margin:2px 4px 2px 0}
 .granted{background:#e6f4ea;color:#1e7d34} .candidate{background:#fef7e0;color:#a06800}
 .notmet{background:#fde8e8;color:#b42318} .noteval{background:#eef0f3;color:#555}
 table{border-collapse:collapse;width:100%;font-size:14px} td,th{border-bottom:1px solid #eee;padding:7px 8px;text-align:left;vertical-align:top}
 .pass{color:#1e7d34;font-weight:600}.fail{color:#b42318;font-weight:600}.partial{color:#a06800;font-weight:600}
 .nv{background:#fff8f0;border-left:3px solid #f0a020;padding:10px 12px;border-radius:6px}
 code{background:#f0f1f3;padding:1px 5px;border-radius:4px;font-size:13px}
 .adv{background:#f3f0fb;border-left:3px solid #8a6fd6;padding:10px 12px;border-radius:6px}
 ul{margin:6px 0}
</style></head><body><div class="wrap">
<h1>reprobe report — {{ r.submission_id }}</h1>
<div class="muted">{{ r.harness_version }} · {{ r.timestamp }}</div>

<div class="card"><b>Source</b><br>
 <code>{{ r.source.input }}</code> → {{ r.source.resolved_type }}
 · pin <code>{{ r.source.pin.kind }}</code>
 · checksum {{ r.source.checksum_verified }}{% if r.source.anonymized %} · <b>anonymized</b>{% endif %}
 {% for w in r.source.warnings %}<div class="muted">⚠️ {{ w }}</div>{% endfor %}
</div>

<div class="card"><b>Badges</b><br>
 {% set a = r.badges.acm %}
 {% macro chip(label,status) %}<span class="chip {{ {'granted':'granted','candidate':'candidate','not-met':'notmet','not-evaluated':'noteval'}[status] }}">{{ label }}: {{ status }}</span>{% endmacro %}
 {{ chip('Available', a.available) }}{{ chip('Functional', a.functional) }}{{ chip('Reproduced', a.results_reproduced) }}
 {% for n in a.notes %}<div class="muted">ℹ️ {{ n }}</div>{% endfor %}
 <div class="muted" style="margin-top:6px">FAIR — findable: {{ r.badges.fair.findable }} · accessible: {{ r.badges.fair.accessible }} · interoperable: {{ r.badges.fair.interoperable }} · reusable: {{ r.badges.fair.reusable }}</div>
</div>

<div class="card"><b>Environment</b><br>
 {{ r.environment.strategy }} ({{ r.environment.env_provenance }}) · <code>{{ r.environment.image }}</code>
 {% for w in r.environment.warnings %}<div class="muted">⚠️ {{ w }}</div>{% endfor %}
</div>

<div class="card"><b>Steps</b>
 <table><tr><th>Target</th><th>Runner</th><th>Status</th><th>Time</th><th>Verified / not verified</th></tr>
 {% for s in r.steps %}
 <tr><td><code>{{ s.target }}</code></td><td>{{ s.runner }}{% if s.tier_reached %}<br><span class="muted">{{ s.tier_reached }}</span>{% endif %}</td>
 <td class="{{ {'pass':'pass','fail':'fail','error':'fail','timeout':'fail','partial':'partial','skipped':'partial'}.get(s.status,'') }}">{{ s.status }}</td>
 <td>{{ s.duration_s }}s</td>
 <td>{% for c in s.claims %}✓ {{ c }}<br>{% endfor %}{% for c in s.not_verified %}<span class="muted">✗ {{ c }}</span><br>{% endfor %}
 {% if s.diagnostics.llm_advisory %}<div class="adv" style="margin-top:6px">💡 <b>diagnosis (advisory):</b> {{ s.diagnostics.llm_advisory.likely_cause }}{% for f in s.diagnostics.llm_advisory.suggested_fixes %}<br>→ {{ f }}{% endfor %}</div>{% endif %}</td></tr>
 {% else %}<tr><td colspan="5" class="muted">no runnable steps executed</td></tr>{% endfor %}
 </table>
</div>

{% if r.llm.summary %}<div class="card"><b>Summary</b>
 <div class="adv">{{ r.llm.summary }}<div class="muted">— {{ r.llm.model }}; LLM-advisory, not a verified fact</div></div></div>{% endif %}

<div class="card"><b>What was NOT checked</b>
 <div class="nv"><ul>{% for x in not_verified %}<li>{{ x }}</li>{% endfor %}</ul></div></div>

<div class="card"><b>Verdict:</b> {{ r.verdict.overall }} · human review required: {{ r.verdict.human_review_required }}</div>
<div class="muted">Generated by reprobe. The harness grants only <i>Available</i> automatically; everything deeper is a candidate for a human.</div>
</div></body></html>""")


def render(r: Report) -> str:
    nv = sorted({x for s in r.steps for x in s.not_verified} | set(r.not_verified))
    return _TPL.render(r=r, not_verified=nv)
